# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_column='cc', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('_bounding_box', models.CharField(db_column='extent', max_length=5000)),
                ('vola_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centre_id', models.CharField(max_length=10)),
                ('var_id', models.PositiveSmallIntegerField()),
                ('observationdate', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.PositiveSmallIntegerField()),
                ('bg_dep', models.FloatField()),
            ],
            options={
                'db_table': 'nwpdata',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=10)),
                ('date', models.DateField(db_column='mydate')),
                ('varid', models.IntegerField()),
                ('filetype', models.CharField(max_length=20)),
            ],
            options={
                'managed': True,
                'db_table': 'period',
                'ordering': ['date', 'center', 'filetype'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('wigosid', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stationtype', models.CharField(max_length=10)),
                ('nrExp0', models.IntegerField()),
                ('nrExp6', models.IntegerField()),
                ('nrExp12', models.IntegerField()),
                ('nrExp18', models.IntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('country', models.ForeignKey(db_column='iso3', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wdqms.Country')),
            ],
            options={
                'managed': True,
                'db_table': 'station',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wdqms.Station'),
        ),
    ]
