# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
    ]
