# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 15:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0002_auto_20180929_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
