# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 18:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0003_station_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='observation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
