# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 22:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0004_auto_20180929_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrObservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('centre', models.CharField(max_length=10)),
                ('varid', models.PositiveSmallIntegerField()),
                ('assimilationdate', models.DateTimeField()),
                ('wigosid', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('invola', models.BooleanField()),
                ('nr_expected', models.PositiveSmallIntegerField()),
                ('nr_received', models.PositiveSmallIntegerField()),
                ('nr_used', models.PositiveSmallIntegerField()),
                ('nr_passive', models.PositiveSmallIntegerField()),
                ('nr_rejected', models.PositiveSmallIntegerField()),
                ('nr_blacklisted', models.PositiveSmallIntegerField()),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wdqms.Station')),
            ],
            options={
                'db_table': 'nwpdatabyperiod',
            },
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='centre_id',
            new_name='centre',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='var_id',
            new_name='varid',
        ),
        migrations.AddField(
            model_name='observation',
            name='wigosid',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
