# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0005_auto_20180929_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrobservation',
            name='wigosid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
