# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0007_auto_20180929_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrobservation',
            old_name='nr_blacklisted',
            new_name='nr_never_used',
        ),
        migrations.RenameField(
            model_name='nrobservation',
            old_name='nr_passive',
            new_name='nr_no_content',
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='bg_dep',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_not_used',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_other_issue',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_quality_issue',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_rejected_da',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_thinned',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='nr_used_alt',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
