# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0008_auto_20180929_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_expected',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_never_used',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_no_content',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_not_used',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_other_issue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_quality_issue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_received',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_rejected',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_rejected_da',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_thinned',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_used',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nrobservation',
            name='nr_used_alt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
