# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0009_auto_20180929_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrobservation',
            name='bg_dep',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bg_dep',
            field=models.FloatField(null=True),
        ),
    ]
