# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0010_auto_20180930_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrobservation',
            name='isempty',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
