# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0011_nrobservation_isempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrobservation',
            name='hasduplicate',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
