# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0012_nrobservation_hasduplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='varid',
        ),
        migrations.AddField(
            model_name='nrobservation',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wdqms.Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wdqms.Period'),
            preserve_default=False,
        ),
    ]
