# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0013_auto_20180930_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField()),
                ('oid', models.IntegerField()),
                ('table_schema', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('row_estimate', models.FloatField()),
                ('total_bytes', models.BigIntegerField()),
                ('index_bytes', models.BigIntegerField()),
                ('toast_bytes', models.BigIntegerField()),
                ('table_bytes', models.BigIntegerField()),
                ('total', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dbstats',
            },
        ),
    ]
