# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0014_dbstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbstats',
            name='toast',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='index',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='table',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='total',
            field=models.CharField(max_length=50),
        ),
    ]
