# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0015_auto_20180930_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstats',
            name='index_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='table_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='toast_bytes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='total_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
