# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-30 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0016_auto_20180930_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstats',
            name='createdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='index',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='oid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='row_estimate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='table',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='table_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='table_schema',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='toast',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dbstats',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
