# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0017_auto_20180930_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstats',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='period',
            name='date',
            field=models.DateTimeField(db_column='mydate'),
        ),
    ]
