# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 11:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0019_create_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrobservation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326),
        ),
        migrations.AlterField(
            model_name='observation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_column='geom', srid=4326),
        ),
    ]
