# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0020_auto_20181129_1132'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nrobservation',
            index=models.Index(fields=['assimilationdate', 'centre', 'hasduplicate', 'varid'], name='nwpdatabype_assimil_857830_idx'),
        ),
    ]
