# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0021_auto_20181129_1147'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nrobservation',
            name='nwpdatabype_assimil_857830_idx',
        ),
        migrations.AddIndex(
            model_name='nrobservation',
            index=models.Index(fields=['assimilationdate'], name='nwpdatabype_assimil_aa9376_idx'),
        ),
        migrations.AddIndex(
            model_name='nrobservation',
            index=models.Index(fields=['centre'], name='nwpdatabype_centre_076330_idx'),
        ),
        migrations.AddIndex(
            model_name='nrobservation',
            index=models.Index(fields=['location'], name='nwpdatabype_geom_2fffdf_idx'),
        ),
    ]
