# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0022_auto_20181129_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='nrExp0',
        ),
        migrations.RemoveField(
            model_name='station',
            name='nrExp12',
        ),
        migrations.RemoveField(
            model_name='station',
            name='nrExp18',
        ),
        migrations.RemoveField(
            model_name='station',
            name='nrExp6',
        ),
        migrations.AddField(
            model_name='station',
            name='schedules',
            field=models.TextField(blank=True, default=False),
        ),
    ]
