# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0023_auto_20181130_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='schedules',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
