# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0024_auto_20181130_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='schedules',
            field=models.TextField(),
        ),
    ]
