# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0025_auto_20181130_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
