# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdqms', '0026_period_processed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nrobservation',
            name='nwpdatabype_centre_076330_idx',
        ),
        migrations.RenameField(
            model_name='nrobservation',
            old_name='centre',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='centre',
            new_name='center',
        ),
        migrations.AddIndex(
            model_name='nrobservation',
            index=models.Index(fields=['center'], name='nwpdatabype_center_6c3dc2_idx'),
        ),
    ]
